### ISSUE TITLE
memory leak with each move?

### ISSUE THREAD

**Issue by zeakzz** [RuolinZheng08/renpy-chess#17]
every time i move a piece the games ram usage goes up by about 100 mb. is there any plan to fix this?

**Comment by RuolinZheng08** [comment]
#16 I attempted to fix it but it might be a bug in this particular version of the package https://python-chess.readthedocs.io/en/v0.23.10/. I can't switch to a higher version because this is the last version that supports Python 2 (which Ren'Py uses).
You are welcome to look into it if you have some bandwidth, as I currently don't have the bandwidth to investigate further.

**Comment by zeakzz** [comment]
since renpy 7.4.3 it has allowed compatibility with python 3 and is planning on full support in 8.0

**Comment by RuolinZheng08** [comment]
7.4 only provides very limited compatibility and that wasn't sufficient for a full upgrade of the package.

**Comment by zeakzz** [comment]
oh i see, are there plans to upgrade once renpy 8.0 comes out?

**Comment by zeakzz** [comment]
I may have found the source of the memory leak, is there a way to make these console window hosts that spam up during a game expire? or perhaps a fix on your end that would make less of them appear? because im having a issue where even after a chess game is over the game will be extremely slow until it is restarted.
![unknown](https://user-images.githubusercontent.com/63619162/127847550-ac3dc38f-4c7b-4134-841d-b00cb7d16fef.png)

It seems to open a new window host every time i move a piece and it also opens a new stockfish and pythonw process, which is very memory consuming.
